name: Publish Package
on:
    release:
        types: [published]

env:
    PKG_NAME: avqol
    MANIFEST_FILE_PATH: dist/module.json
    RELEASE_NAME: ${{ github.event.release.tag_name }}

jobs:
    run-action:
        name: Run action
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: "npm"
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Zip Files
              working-directory: ./dist
              run: zip -r ./${{env.PKG_NAME}}.zip ./*
            - name: upload binaries to release
              uses: softprops/action-gh-release@v1
              if: ${{startsWith(github.ref, 'refs/tags/') }}
              with:
                  files: ./dist/${{env.PKG_NAME}}.zip ./dist/module.json

            - name: Upload release artifacts
              uses: Roang-zero1/github-upload-release-artifacts-action@v2
              with:
                  args: "dist/bin/ dist/shell/compiled.sh"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish Module to FoundryVTT Website
              uses: Varriount/fvtt-autopublish@v1.1.1
              with:
                  username: ${{ secrets.FOUNDRY_ADMIN_USERNAME }}
                  password: ${{ secrets.FOUNDRY_ADMIN_PASSWORD }}
                  module-id: ${{ secrets.FOUNDRY_ADMIN_MODULE_ID }}
                  manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_NAME }}/module.json
                  manifest-file: ${{ env.MANIFEST_FILE_PATH }}
